### ISSUE TITLE
Proposal: Ensure that code is formatted before publish CI

### ISSUE THREAD

**Issue by samjowen** [chrisgreg/bloom#16]
Hi @chrisgreg , seeing as this is a repository that shares common goals with shadcn's library — code ownership for the users, I think it would be a good idea to ensure that the code in this repository is always formatted before publishing.

Therefore, I propose adding a CI step that looks something like this as part of the build or publish job:

```yml
      # Step: Check that the checked in code has already been formatted.
      # This step fails if something was found unformatted.
      - name: Check Formatting
        run: mix format --check-formatted
```

What do you think?
